/** GENERATED by scripts/export-abi.mjs — do not edit by hand. */
export const SettlementVaultAbi = [
  {
    type: "constructor",
    inputs: [
      {
        name: "corpshift_",
        type: "address",
        internalType: "contract ICorpShift",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "acceptOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claim",
    inputs: [
      {
        name: "settlementId",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "payout",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimedUnits",
    inputs: [
      {
        name: "",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "closeSettlement",
    inputs: [
      {
        name: "settlementId",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "corpshift",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract ICorpShift",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "covers",
    inputs: [
      {
        name: "settlementId",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "holder",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "entitlementOf",
    inputs: [
      {
        name: "settlementId",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "holder",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "units",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "payout",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "fundSettlement",
    inputs: [
      {
        name: "settlementId",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getSettlement",
    inputs: [
      {
        name: "settlementId",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct SettlementVault.Settlement",
        components: [
          {
            name: "actionId",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "asset",
            type: "address",
            internalType: "address",
          },
          {
            name: "paymentToken",
            type: "address",
            internalType: "contract IERC20",
          },
          {
            name: "ratePerUnit",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "snapshotFactor",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "operator",
            type: "address",
            internalType: "address",
          },
          {
            name: "openedAt",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "closesAt",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "totalFunded",
            type: "uint128",
            internalType: "uint128",
          },
          {
            name: "totalClaimed",
            type: "uint128",
            internalType: "uint128",
          },
          {
            name: "open",
            type: "bool",
            internalType: "bool",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "openSettlement",
    inputs: [
      {
        name: "actionId",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "paymentToken",
        type: "address",
        internalType: "address",
      },
      {
        name: "ratePerUnit",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "closesAt",
        type: "uint64",
        internalType: "uint64",
      },
    ],
    outputs: [
      {
        name: "settlementId",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pendingOwner",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "settlementCount",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "settlementIds",
    inputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [
      {
        name: "newOwner",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "EntitlementClaimed",
    inputs: [
      {
        name: "settlementId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "holder",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "units",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "payout",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferStarted",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SettlementClosed",
    inputs: [
      {
        name: "settlementId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "remainderSwept",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SettlementFunded",
    inputs: [
      {
        name: "settlementId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "funder",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SettlementOpened",
    inputs: [
      {
        name: "settlementId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "actionId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "asset",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "paymentToken",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "ratePerUnit",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "snapshotFactor",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "operator",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "InvalidRate",
    inputs: [],
  },
  {
    type: "error",
    name: "NotSettlementOperator",
    inputs: [
      {
        name: "id",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "NothingToClaim",
    inputs: [
      {
        name: "id",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "Reentrancy",
    inputs: [],
  },
  {
    type: "error",
    name: "SettlementClosed_",
    inputs: [
      {
        name: "id",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "SettlementNotFound",
    inputs: [
      {
        name: "id",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "SettlementStillOpen",
    inputs: [
      {
        name: "id",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "TransferFailed",
    inputs: [
      {
        name: "token",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "TransferFromFailed",
    inputs: [
      {
        name: "token",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "Unauthorized",
    inputs: [],
  },
  {
    type: "error",
    name: "Underfunded",
    inputs: [
      {
        name: "id",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "required",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "available",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "ZeroAddress",
    inputs: [],
  },
] as const;
