#!/usr/bin/env node
/**
 * Extracts contract ABIs from forge artifacts (packages/contracts/out/*.json)
 * into typed TS modules under packages/sdk/src/abi/. Run after `forge build`.
 * Keeps the SDK ABI in lockstep with the compiled contracts.
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(root, "packages/contracts/out");
const DEST = join(root, "packages/sdk/src/abi");

const CONTRACTS = [
  "CorpShiftRegistry",
  "PolicyEngine",
  "SettlementVault",
  "NaiveVault",
  "CorpShiftAwareVault",
  "MockStockToken",
  "MockUSDG",
  "MockPriceOracle",
  "IERC8056",
  "IAssetAdapter",
];

mkdirSync(DEST, { recursive: true });

let count = 0;
for (const name of CONTRACTS) {
  const artifact = JSON.parse(readFileSync(join(OUT, `${name}.sol/${name}.json`), "utf8"));
  const ts = `/** GENERATED by scripts/export-abi.mjs — do not edit by hand. */\nexport const ${name}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
  writeFileSync(join(DEST, `${name}.ts`), ts);
  count++;
}

writeFileSync(
  join(DEST, "index.ts"),
  `/** GENERATED by scripts/export-abi.mjs — do not edit by hand. */\n${CONTRACTS.map((n) => `export { ${n}Abi } from "./${n}.js";`).join("\n")}\n`,
);
console.log(`exported ${count} ABIs → ${DEST}`);
